-- RADA CREST SHOP — Supabase production starter schema
-- Run this entire file in Supabase SQL Editor.
-- Then create the first admin in Authentication > Users and run the final UPDATE.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text,
  price numeric(12,2) not null check (price >= 0),
  old_price numeric(12,2) check (old_price is null or old_price >= price),
  image_url text,
  stock integer not null default 0 check (stock >= 0),
  warranty text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  status text not null default 'pending'
    check (status in ('pending','confirmed','packed','shipped','delivered','cancelled')),
  payment_method text not null default 'cod'
    check (payment_method in ('cod','online')),
  total numeric(12,2) not null check (total >= 0),
  shipping_name text,
  shipping_phone text,
  shipping_address text,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0)
);

-- Auto-create a customer profile whenever a user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.phone, new.raw_user_meta_data ->> 'phone', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Secure role check. Authorization data lives in profiles, not editable user metadata.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Profiles
drop policy if exists "profile own select" on public.profiles;
create policy "profile own select" on public.profiles
for select to authenticated
using ((select auth.uid()) = id or (select public.is_admin()));

drop policy if exists "profile own update" on public.profiles;
create policy "profile own update" on public.profiles
for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

-- Products: everyone can see active products; only admins manage products.
drop policy if exists "public active products" on public.products;
create policy "public active products" on public.products
for select to anon, authenticated
using (active = true or (select public.is_admin()));

drop policy if exists "admin product insert" on public.products;
create policy "admin product insert" on public.products
for insert to authenticated
with check ((select public.is_admin()));

drop policy if exists "admin product update" on public.products;
create policy "admin product update" on public.products
for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "admin product delete" on public.products;
create policy "admin product delete" on public.products
for delete to authenticated
using ((select public.is_admin()));

-- Orders: customer can create/read only their own; admins can manage all.
drop policy if exists "own orders select" on public.orders;
create policy "own orders select" on public.orders
for select to authenticated
using ((select auth.uid()) = user_id or (select public.is_admin()));

drop policy if exists "own orders insert" on public.orders;
create policy "own orders insert" on public.orders
for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "admin orders update" on public.orders;
create policy "admin orders update" on public.orders
for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

-- Order items: customers may read items belonging to their own order; admins may manage.
drop policy if exists "own order items select" on public.order_items;
create policy "own order items select" on public.order_items
for select to authenticated
using (
  exists (
    select 1 from public.orders o
    where o.id = order_id
      and (o.user_id = (select auth.uid()) or (select public.is_admin()))
  )
);

drop policy if exists "own order items insert" on public.order_items;
create policy "own order items insert" on public.order_items
for insert to authenticated
with check (
  exists (
    select 1 from public.orders o
    where o.id = order_id and o.user_id = (select auth.uid())
  )
);

-- Least-privilege grants for browser roles.
grant select on public.products to anon, authenticated;
grant select on public.profiles to authenticated;
grant update (full_name, phone) on public.profiles to authenticated;
grant select, insert on public.orders to authenticated;
grant update (status) on public.orders to authenticated;
grant select, insert on public.order_items to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Starter products
insert into public.products (name,category,description,price,old_price,stock,warranty,active)
select * from (values
('RADA CREST 9W LED Bulb','LED Bulbs','Energy-efficient everyday LED bulb.',149,199,100,'1 Year',true),
('RADA CREST 12W LED Bulb','LED Bulbs','Bright modern LED bulb.',179,229,100,'1 Year',true),
('RADA CREST LED Panel Light','LED Lights','Clean modern lighting for homes.',399,499,50,'1 Year',true),
('RADA CREST 4-Way Extension Board','Extension Boards','Daily-use multi-socket extension board.',349,449,50,'1 Year',true)
) v(name,category,description,price,old_price,stock,warranty,active)
where not exists (select 1 from public.products);

-- FIRST ADMIN:
-- 1) Create the admin user in Supabase Dashboard > Authentication > Users.
-- 2) Copy that user's UUID.
-- 3) Run:
-- update public.profiles set role='admin' where id='PASTE_ADMIN_USER_UUID';
--
-- IMPORTANT: Do not create an admin signup form. Admin accounts should be created by the owner.
